#!/bin/sh

sxhkd &
sh $HOME/.config/picom/launch.sh &
#redshift -l 38.642780:-121.270172
wal -i $HOME/Pictures/wallpaper1.jpg &
xrdb -merge $HOME/.Xresources &
sh $HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 5
bspc config window_gap 50
bspc config top_padding 100
bspc config left_padding 60
bspc config right_padding 60
bspc config border_radius 20

#get xrdb colors
highlight=$(xrdb -query | grep "*.highlight" | cut -f 2)
background=$(xrdb -query | grep "*.background-no-transparancy:" | cut -f 2)

bspc config focused_border_color "$highlight"
bspc config normal_border_color "$background"

bspc config focus_follows_pointer true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false


bspc rule -a mpv state=floating
bspc rule -a ripcord state=floating
